DROP TABLE faktury CASCADE CONSTRAINTS;

DROP TABLE faktury_pozycje CASCADE CONSTRAINTS;

DROP TABLE grupy_produktowe CASCADE CONSTRAINTS;

DROP TABLE grupy_wiekowe CASCADE CONSTRAINTS;

DROP TABLE klienci CASCADE CONSTRAINTS;

DROP TABLE producenci CASCADE CONSTRAINTS;

DROP TABLE produkty CASCADE CONSTRAINTS;

DROP SEQUENCE PRODUCENCI_SEQ;

DROP SEQUENCE GRUPY_PRODUKTOWE_SEQ;

DROP SEQUENCE PRODUKTY_SEQ;

DROP SEQUENCE FAKTURY_SEQ;

DROP SEQUENCE GRUPY_WIEKOWE_SEQ;

DROP SEQUENCE KLIENCI_SEQ;

DROP FUNCTION data_faktury_fun;

DROP FUNCTION id_klienta_fun;

DROP FUNCTION id_produktu_fun;

DROP PROCEDURE generator;

DROP VIEW Zestawienie_sprzedazy;

DROP VIEW Stan_magazynu;

DROP VIEW Zyski;

DROP VIEW Zestawienie_sprzedazy_krzyzowo;
